AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Keykeeper

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  SecretKeyParameterStorePath:
    Type: String
    Default: "keykeeper/1"

Resources:

  # allow everyone to read the items in the bucket
  PublicKeysBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublicKeysBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub '${PublicKeysBucket.Arn}/*'
            Principal: '*'

  PublicKeysBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "keykeeper-issuer-${AWS::Region}"
      AccessControl: PublicRead
      MetricsConfigurations:
        - Id: EntireBucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  CreateIssuerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: keykeeper/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PublicKeysBucket
        - Statement:
            - Effect: Allow
              Action: ssm:PutParameter
              Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${SecretKeyParameterStorePath}"

      Environment:
        Variables:
          PublicKeysBucket: !Ref PublicKeysBucket
          IssuerDomain: !GetAtt PublicKeysBucket.DomainName
          SecretKeyParameterStorePath: !Ref SecretKeyParameterStorePath

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateIssuerFunction:
    Description: "Lambda to initiazile a new issuer with single key"
    Value: !Ref CreateIssuerFunction
  KeyKeeperIssuerBucket:
    Description: "The issuer bucket with public keys"
    Value: !Ref PublicKeysBucket
  BucketUrl:
    Description: "Issuer url (you should point your Authorizer at this location"
    Value: !Sub
      - "https://${domain}"
      - domain: !GetAtt PublicKeysBucket.DomainName
  SecretKeyParameterStorePath:
    Description: "Location of the secret key in parameter store"
    Value: !Ref SecretKeyParameterStorePath